### ISSUE TITLE
Ability to define error messages inline

### ISSUE THREAD

**Issue by mpscholten** [mpscholten/request-parser#16]
See #11

`$name = $this->queryParameter('name')->string()->required("Invalid parameter name, expected a valid name but got {value}", "Parameter name not found");`

**Comment by gausam** [comment]
So was thinking from Laravel-land about the custom error messages in my comment in the [other issue](https://github.com/mpscholten/request-parser/issues/11). In Laravel you'd define the rules in one array, and then the messages in another. But here our way of defining validation rules is different so the first thing I could think of was inline. You'll have to decide on the best implementation.

For example if my rule is `$this->queryParameter('page')->int()->required();`, and the user submits their request with `?page=loremipsum` the library will throw `Parameter page not found` - even though technically it's there. So I don't know how we can maybe make each of the validation parsers to have a sensible default that they throw (which can also be overridden). So that instead of `Parameter page not found` in this case, we'd have a more intelligible message telling the user page must be an integer. Or if that's too much responsibility to cast onto the library then each parser can throw its own exception type somehow so that the developer can catch the exception and know which validation failed first in the chain.

&lt;/ 0.00000000002 cents &gt;

**Comment by mpscholten** [comment]
Totally agree, a more granular exception hierarchy would make sense. I'll take a look at how we can do it without breaking b.c.

Btw: The reason why it's currently not built-in is that at quintly where this library was initially built, our javascript based client always handles the validation and shows user friendly error messages (the server side is also validating, but not with nice error messages). So we never had the need for this.

Thanks again for the suggestion 👍

**Comment by gausam** [comment]
I see. yeah that makes sense. It's not a show-stopper in any way for what I'm building, because I'm validating at most 5 or so inputs at a time (it's an API) - so catching the few validation exceptions for those is not a problem.

**Comment by mpscholten** [comment]
Merged via #26. However not released yet :)

**Comment by gausam** [comment]
Awesome! Will play with it soon.

Meanwhile: RequestParser has gobbled up the last 3 hours for me! There's a [mobile app](http://smssync.ushahidi.com/developers/) I send a very simple JSON object back to with a structure like `{ 'payload': { 'success': true} }`. My browser, Postman and a lot of other tools agree my app is sending the same old JSON object. BUT the app is not. I mean if I send back the response object after having run any line with `$this->bodyParameter('field')->validationsetc()` I don't know how/where RequestParser puts itself in the response picture in a way the app doesn't like. But without such a line app can clearly read the response coming from the server.

**Comment by gausam** [comment]
Actually. Let me investigate that some more. Then come back with a more solid (and hopefully reproducible) description of what's going on.

**Comment by mpscholten** [comment]
Hm, RequestParser should never touch the response. Have you tried comparing the complete raw http responses between non-request-parser based code and request-parser based code?

Basically doing a `curl -vvv http://example.com/request-parser-based-code` and a `curl -vvv http://example.com/not-request-parser-based-code` and then looking for differences.

> Actually. Let me investigate that some more. Then come back with a more solid (and hopefully reproducible) description of what's going on.

Would be cool if you can find build a small code example (in case you cannot share some code for business reasons here on GitHub, feel free to send me a mail (marc@quintly.com))

**Comment by mpscholten** [comment]
@ihatehandles just a bit curious: did you solve the problem? and what caused it? :)

**Comment by gausam** [comment]
Hi. I don't know what caused it, but removing some validations resolved it (although I didn't want to). Maybe I had chained them unnaturally, but the chains didn't go beyond the standard two in the examples!

I'll dig up the lines I removed and show them to you.
